---
title: Portfolio of Adoline McCammon
timezone: America/Denver
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
subtitle: Currently running from Jekyll
description: This is the WIP Portfolio site of Adoline McCammon, and is currently
  running from a Jekyll instance.
author: Adoline McCammon
email: ado.forgets@gmail.com
avatar: assets/images/avatar.png
incremental: false
baseurl: 
url: http://192.168.1.37:4000/
twitter_url: 
facebook_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
github_url: 
pinterest_url: 
slack_url: 
dribbble_url: 
google_analytics: 
theme: jekyll-theme-prologue
host: 192.168.1.37
port: 4000
